### ISSUE TITLE
Google Drive fails 

### ISSUE THREAD

**Issue by patriclougheed** [povsod/mahara-artefact-cloud#3] opened 2016-02-23 20:35 UTC
Really like the updates done to the UI! Dropbox working great but Drive fails when trying to authorize.

[WAR] 17 (lib/dml.php:931) Failed to get a recordset: postgres8 error: [-1: ERROR:  null value in column "value" violates not-null constraint] in EXECUTE("UPDATE "usr_account_preference" SET "value" = ?  WHERE "usr" = ?  AND "field" = ? ")
Command was: UPDATE "usr_account_preference" SET "value" = ?  WHERE "usr" = ?  AND "field" = ?  and values was (,1,lasteditedview)

Call stack (most recent first):
set_field_select("usr_account_preference", "value", null, " WHERE "usr" = ? AND "field" = ? ", array(size 2)) at /var/www/folioz_beta/htdocs/lib/dml.php:911
set_field("usr_account_preference", "value", null, "usr", "1", "field", "lasteditedview") at /var/www/folioz_beta/htdocs/lib/user.php:90

set_account_preference("1", "lasteditedview", null) at /var/www/folioz_beta/htdocs/auth/user.php:463
User->set_account_preference("lasteditedview", null) at /var/www/folioz_beta/htdocs/artefact/cloud/blocktype/googledrive/account.php:29

**Comment by anzeljg** [comment] 2016-02-23 20:57
I see.

The problem is that set_account_preference function sets last edited view to null after authorization. This is supported in MySQl, but apparently not in PostgreSQL. I have changed that to 0 instead of null. It should work.,, Will also try to fix ownCloud issue, before releasing the updated version.

**Comment by patriclougheed** [comment] 2016-02-24 04:22
Tried it and it does seem to eliminate the problem.

**Comment by anzeljg** [comment] 2016-02-27 12:55
Issue resolved in latest versions of the plugin:
- for Mahara 15.04: https://github.com/povsod/mahara-artefact-cloud/releases/tag/v15.04.2
- for Mahara 15.10: https://github.com/povsod/mahara-artefact-cloud/releases/tag/v15.10.1

**Closed as completed by anzeljg** 2016-02-27 12:55 UTC
Labels: bug
